#lang racket #| CSC324 Fall 2018: Exercise 4 |#
#|
* Before starting, please review the exercise guidelines at
http://www.cs.toronto.edu/~lczhang/324/assignments.html *
|#
;-------------------------------------------------------------------------------
(provide calculate eval-calc analyze-strictness)

;-------------------------------------------------------------------------------
; * Task 1: Eager Evaluation *
;-------------------------------------------------------------------------------

#|
(calculate expr)
  expr: A datum representing an expression generated by the
        grammar in the Exericse 4 handout
|#
(define (calculate expr)
  (eval-calc expr (hash)))

#|
(eval-calc expr env)
  expr: A datum representing an expression generated by the
        grammar in the Exercise 4 handout
  env:  A hash table representing an environment.
        The keys of the hash table are symbols representing identifiers.

  You may assume that if an `expr` is an identifier, then it is present in `env`.
|#
(define (symbol-finder fn)
  (cond
    [(equal? fn '+) +]
    [(equal? fn '-) -]
    [(equal? fn '*) *]
    [(equal? fn '/) /]
    [(equal? fn '=) =]
    [(equal? fn '>) >]
    [(equal? fn '<) <]
    ))

(define (lam-calc lst var env)
(cond
  [(null? lst) env]
  [else (let ([fn (first lst)][v (first var)][rn (rest lst)][rv (rest var)])
  (lam-calc rn rv (hash-set env fn (eval-calc v env)))
   )]))

(define (eval-calc expr env)
  (cond
    [(null? expr) 0]
    ;[(equal? (first expr) ) (print expr)]
    [(number? expr) expr]
    [(symbol? expr) (hash-ref env expr)]
    [else (let([fn (first expr)] [rn (rest expr)])
            (cond
              [(equal? fn 'let*)
               (cond
                 [(and(equal? (length (first rn)) 1) (number? (cadr (first (first rn)))))
                  (eval-calc (second rn) (hash-set env (car (first (first rn))) (cadr (first (first rn)))))]
                 [(equal? (length (first rn)) 1) (eval-calc (second rn) (hash-set env (car (first (first rn))) (eval-calc (cadr (first (first rn))) env)))]
                 [(and(equal? (length (first rn)) 2) (number? (cadr (first (first rn)))) (number? (cadr (second (first rn)))))
                  (eval-calc (second rn) (hash-set* env (car (first (first rn))) (cadr (first (first rn))) (car (second (first rn))) (cadr (second (first rn)))))
                  ]
                 [(and(equal? (length (first rn)) 2) (number? (cadr (second (first rn)))))
                  (eval-calc (second rn) (hash-set* env (car (first (first rn))) (eval-calc (cadr (first (first rn))) env) (car (second (first rn))) (cadr (second (first rn)))))
                  ]
                 [(and(equal? (length (first rn)) 2) (number? (cadr (first (first rn)))))
                  (eval-calc (second rn) (hash-set* env (car (first (first rn))) (cadr (first (first rn))) (car (second (first rn))) (eval-calc (cadr (second (first rn))) env)))
                  ]
                 [(and(equal? (length (first rn)) 2))
                  (eval-calc (second rn) (hash-set* env (car (first (first rn))) (eval-calc (cadr (first (first rn))) env) (car (second (first rn))) (eval-calc (cadr (second (first rn))) env)))
                  ]
                 )]
              [(equal? fn 'if)
               (if((symbol-finder (first (first rn)))
                   (eval-calc (second (first rn)) env) (eval-calc (third (first rn)) env)) (eval-calc (second rn) env) (eval-calc (third rn) env))]
              [(or (equal? fn '+) (equal? fn '-) (equal? fn '/) (equal? fn '*))
               (cond
                 [(and (number? (first rn))(number? (second rn))) ((symbol-finder fn) (first rn) (second rn))]
                 [(and (number? (first rn))(symbol? (second rn))) ((symbol-finder fn) (first rn) (eval-calc (second rn) env))]
                 [(and (symbol? (first rn))(number? (second rn))) ((symbol-finder fn) (eval-calc (first rn) env) (second rn))]
                 [(and (symbol? (first rn))(symbol? (second rn))) ((symbol-finder fn) (eval-calc (first rn) env) (eval-calc (second rn) env))]
                 [(and (symbol? (first rn))(list? (second rn))) ((symbol-finder fn) (eval-calc (first rn) env) (eval-calc (second rn) env))]
                 [(and (list? (first rn))(symbol? (second rn))) ((symbol-finder fn) (eval-calc (first rn) env) (eval-calc (second rn) env))]
                 [(and (number? (first rn))(list? (second rn))) ((symbol-finder fn) (first rn) (eval-calc (second rn) env))]
                 [(and (list? (first rn))(number? (second rn))) ((symbol-finder fn) (eval-calc (first rn) env) (second rn))]
                 [(and (list? (first rn))(list? (second rn))) ((symbol-finder fn) (eval-calc (first rn) env) (eval-calc (second rn) env))]
                 )]
              [(equal? (car fn) 'closure)
              (eval-calc (third (cadr fn)) env)
              ]
              [else
              (let ([lst (second fn)][expr (third fn)][var rn])
              (eval-calc (list (append (list) '(closure) (list fn) (lam-calc lst var env))) (lam-calc lst var env))
              )]
              ))]))

(module+ test
  (require rackunit)
  ; You should write more tests to make sure that your
  ; interpreter uses lexical scoping

  (test-equal? "Function definition"
               (calculate '((lambda (a) (+ a 1)) 4))
               5)
  (test-equal? "Functions with multiple arguments"
               (calculate '((lambda (a b) (+ b 1)) 4 14))
               15))

;-------------------------------------------------------------------------------
; * Task 1: Strictness analysis *
;-------------------------------------------------------------------------------
#|
(analyze-strictness func-defs)
  func-defs:
      A datum representing a program as specified by the grammar on the handout.
      (In this case, it's a list of function definitions.)

  Returns a *strictness map*, which is a hash table mapping function names (as symbols)
  to a list of indexes of the strict parameters of that function.
  Each list should be in increasing order.

  Remember, you may assume that the program has no syntactic or semantic errors
  (so you don't even need to watch out for things like duplicate names).

  Hash table reference: https://docs.racket-lang.org/reference/hashtables.html.

  Implementation hints:
    1. Same as Exercise 3, the main work can be done by processing the list of
       function definitions in a call to foldl.
    2. Working with list indexes is a bit more annoying in pure functional land.
       Use the list function `indexes-where`, which is similar to `filter` except
       it returns indexes rather than elements.
|#
;input: lst:the identifiers, rest: the expression 
;output: list
(define (as-helper s-map lst res orig)
(cond
  [(null? lst) (list)]
  [else(let* ([fn (first lst)][rn (as-helper s-map (rest lst) res orig)])
  (if (strict-in? s-map fn res)(append rn (indexes-of orig fn)) rn)
  )]))


(define (strict-in? s-map id expr)
  (cond
  [(number? expr) #f]
  [(symbol? expr) (if (equal? expr id) #t #f)]
  [(equal? (first expr) 'if)
   (let* ([cif (second expr)][tif (third expr)] [eif (fourth expr)])
     (cond
       [(strict-in? s-map id cif) #t]
       [(and (strict-in? s-map id tif) (strict-in? s-map id eif)) #t]
       [else #f]
   ))]
  [(equal? (first expr) '+)
   (if (> (checkplus s-map id (rest expr)) 0) #t #f)
   ]
  [else
   #t
    ]))

(define (checkplus s-map id expr)
(cond
  [(null? expr) 0]
  [else(let* ([fn (first expr)][rn (checkplus s-map id (rest expr))])
  (if (strict-in? s-map id fn)(+ 1 rn) rn)
         )]))

(define (analyze-strictness func-defs)
  (cond
    [(null? func-defs) (hash)]
    [else (let* [(fn (first func-defs)) (func (first (second fn)))(lst (rest (second fn)))(rn (third fn))]
    (hash-set (hash) func (reverse (as-helper (hash) lst rn lst)))
    ;(print fn)
    ;(print func)(print lst)(print rn)
    )]))


;(analyze-strictness '((define (f x) x)))
;(analyze-strictness '((define (f x y z) (+ x y))))

#|
(strict-in? s-map id expr)
  s-map: A strictness map
  id: An identifier
  expr: A quoted expression in the grammar specified by the assignment handout.

  Returns whether id is strict in the given expression.
  Uses the given strictness map to determine strictness in function calls.

  NOTE: this function isn't being tested explicitly, so you may freely change it or
  ignore it for this exercise.

  Implementation hint:
    Remember that `and` and `or` aren't function identifiers: you can't pass them to
    HOFs like `map` or `apply`. But you can use functions like `andmap` and `ormap`
    to achieve similar effects.
|#


(module+ test
  (require rackunit)

  (test-equal? "Identity function"
               (analyze-strictness '((define (f x) x)))
               (hash
                'f (list 0)))

  (test-equal? "One function, with if (1)"
               (analyze-strictness '((define (f x) (if x 3 5))))
               (hash
                'f (list 0)))

  (test-equal? "One function, with +"
               (analyze-strictness '((define (f x y z) (+ x y))))
               (hash
                'f (list 0 1)))
  )
